version: '3'
services:
  consul-agent:
    image: consul:latest
    container_name: consul_agent
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    networks:
      - my-net
    command: agent -dev -client="0.0.0.0"

  account:
    image: ping/account
    container_name: account
    ports:
      - 8989:8989
    networks:
      - my-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  my-net: